name: my_baby
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_html: ^2.1.0
  webview_flutter: ^2.0.1
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.9
  connectivity: ^3.0.6
  video_player: ^2.0.0
  chewie: ^1.0.0
  charts_flutter: ^0.11.0
  http: ^0.13.3
  flutter_local_notifications: ^6.0.0
  advance_pdf_viewer: ^2.0.0
  logger: ^1.0.0
#  syncfusion_flutter_charts: ^19.1.57+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic